import { useState } from "react";
import Head from "next/head";
import TestComp from "components/TestComp";
import Window from "components/Window";

const Home = (): React.ReactElement => {
  const [showWindow, setShowWindow] = useState(true);
  // we need save points to preserve window location and size!
  // useRnd for wrapping all hooks
  // useDraggable for positioning
  // useSize for sizing
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <link href="/favicon.ico" rel="icon" />
      </Head>
      <main>
        <TestComp />
        {showWindow && <Window setShowWindow={setShowWindow} />}
      </main>
    </>
  );
};
export default Home;
